# Generated by Django 5.2.7 on 2025-10-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentsettings",
            options={"verbose_name": "Payment Settings"},
        ),
        migrations.RenameField(
            model_name="paymentsettings",
            old_name="flutterwave_public_key",
            new_name="nowpayments_api_key",
        ),
        migrations.RenameField(
            model_name="paymentsettings",
            old_name="flutterwave_secret_key",
            new_name="nowpayments_ipn_secret_key",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customization_notes",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_provider",
        ),
        migrations.RemoveField(
            model_name="order",
            name="preferred_platforms",
        ),
        migrations.RemoveField(
            model_name="order",
            name="transaction_ref",
        ),
        migrations.AddField(
            model_name="order",
            name="nowpayments_invoice_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="nowpayments_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
