# Generated by Django 5.2.7 on 2025-10-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_paymentsettings_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="brand_details",
            field=models.TextField(
                blank=True,
                help_text="Client notes on branding, colors, logos, etc.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="core_functionality",
            field=models.TextField(
                help_text="A summary of the project's main purpose and features.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="platform_choice",
            field=models.CharField(
                help_text="The platform selected by the user.", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="project_name",
            field=models.CharField(
                help_text="The requested name for the application.",
                max_length=255,
                null=True,
            ),
        ),
    ]
