# Generated by Django 5.2.7 on 2025-10-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_order_brand_details_order_core_functionality_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsettings",
            name="support_email",
            field=models.EmailField(
                blank=True,
                help_text="The email address for customer support inquiries.",
                max_length=254,
            ),
        ),
    ]
