# Generated by Django 5.2.7 on 2025-10-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="address_availability",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="contact_section_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="contact_section_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="email_response_time",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="form_header_icon",
            field=models.CharField(
                blank=True,
                help_text="Bootstrap icon class e.g. bi bi-chat-dots-fill",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="form_header_paragraph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="form_header_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="info_header_paragraph",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="info_header_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="phone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="phone_availability",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="stat_1_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="stat_1_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="stat_2_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="stat_2_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="stat_3_label",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="stat_3_number",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
