# Generated by Django 5.2.7 on 2025-10-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contact",
            "0002_contactpage_address_contactpage_address_availability_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contactpage",
            name="submit_button_txt",
            field=models.CharField(blank=True, default="Get a Quote", max_length=255),
        ),
    ]
