# Generated by Django 5.2.7 on 2025-10-17 08:08

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_contactpage_submit_button_txt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactpage",
            old_name="info_header_paragraph",
            new_name="info_header_text",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="address",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="address_availability",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="email_response_time",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="phone_availability",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="stat_1_label",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="stat_1_number",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="stat_2_label",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="stat_2_number",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="stat_3_label",
        ),
        migrations.RemoveField(
            model_name="contactpage",
            name="stat_3_number",
        ),
        migrations.AddField(
            model_name="contactpage",
            name="social_connect_title",
            field=models.CharField(
                blank=True, default="Connect With Us", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="ContactMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="The Bootstrap Icon class (e.g., 'bi bi-envelope-at').",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "details",
                    models.CharField(
                        help_text="The contact detail (e.g., email, phone number, or address).",
                        max_length=255,
                    ),
                ),
                (
                    "response_time",
                    models.CharField(
                        help_text="The small text below the detail.", max_length=100
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_methods",
                        to="contact.contactpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactSocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="The Bootstrap Icon class (e.g., 'bi bi-linkedin').",
                        max_length=100,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="contact.contactpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("number", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=100)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_stats",
                        to="contact.contactpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
