# Generated by Django 5.2.7 on 2025-10-14 19:06

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="features",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("feature", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("text", 1), ("icon", 1)]],
                        {},
                    ),
                },
                verbose_name="Service Features",
            ),
        ),
        migrations.AlterField(
            model_name="servicepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading_block", 2), ("paragraph_block", 3), ("image_block", 6)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a header size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "description": "A rich text paragraph",
                            "icon": "pilcrow",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5)]],
                        {},
                    ),
                },
                verbose_name="Service Page Body",
            ),
        ),
    ]
