# Generated by Django 5.2.7 on 2025-10-14 19:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicepage_features_alter_servicepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="features",
            field=wagtail.fields.StreamField(
                [("feature", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("text", 1), ("icon", 1)]],
                        {},
                    ),
                },
                verbose_name="Service Features",
            ),
        ),
    ]
