# Generated by Django 5.2.7 on 2025-10-15 05:31

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_testimonial"),
        ("services", "0004_servicepage_process_title_processstep"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="testimonial",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: select a testimonial to display in the sidebar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="base.testimonial",
            ),
        ),
        migrations.CreateModel(
            name="ServiceDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "fact_label",
                    models.CharField(help_text="e.g. 'Duration'", max_length=100),
                ),
                (
                    "fact_value",
                    models.CharField(help_text="e.g. '3-6 Months'", max_length=100),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_details",
                        to="services.servicepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
