# Generated by Django 5.2.7 on 2025-10-15 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
        ("services", "0005_servicepage_testimonial_servicedetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepage",
            name="contact_form",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: select a form to display in the sidebar.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contact.contactpage",
            ),
        ),
    ]
