# Generated by Django 5.2.7 on 2025-10-15 10:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_servicepage_contact_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_block", 2),
                    ("paragraph_block", 3),
                    ("image_block", 6),
                    ("accordion", 9),
                    ("feature_list", 13),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a header size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "description": "A rich text paragraph",
                            "icon": "pilcrow",
                            "template": "blocks/paragraph_block.html",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Add the title for the accordion item",
                            "required": True,
                        },
                    ),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Add the content for the accordion item",
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 7), ("content", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Add a title for the feature list (e.g., Key Features)",
                            "required": True,
                        },
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {"label": "Feature"}),
                    12: ("wagtail.blocks.ListBlock", (11,), {}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 10), ("features", 12)]],
                        {},
                    ),
                },
                verbose_name="Service Page Body",
            ),
        ),
    ]
