# Generated by Django 5.2.7 on 2025-10-15 13:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_alter_servicepage_body"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyUsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("section_title", models.CharField(default="Why Us", max_length=255)),
                ("section_subtitle", models.TextField(blank=True)),
                (
                    "feature_cards",
                    wagtail.fields.StreamField(
                        [("feature_card", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g., 'bi bi-palette-fill'",
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            2: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            3: ("wagtail.blocks.IntegerBlock", (), {"required": True}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon_class", 0),
                                        ("title", 1),
                                        ("text", 2),
                                        ("stat_number", 3),
                                        ("stat_label", 1),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                ("showcase_title", models.CharField(blank=True, max_length=255)),
                ("showcase_lead_text", models.TextField(blank=True)),
                (
                    "feature_list",
                    wagtail.fields.StreamField(
                        [("feature_item", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "bi bi-check-circle-fill",
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            2: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("icon_class", 0), ("title", 1), ("text", 2)]],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "primary_cta_text",
                    models.CharField(
                        blank=True, default="Start Your Project", max_length=100
                    ),
                ),
                ("primary_cta_link", models.URLField(blank=True)),
                (
                    "secondary_cta_text",
                    models.CharField(
                        blank=True, default="View Portfolio", max_length=100
                    ),
                ),
                ("secondary_cta_link", models.URLField(blank=True)),
                (
                    "showcase_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
