# Generated by Django 5.2.7 on 2025-10-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_alter_whyuspage_primary_cta_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicepage",
            name="badge_text",
        ),
        migrations.RemoveField(
            model_name="servicepage",
            name="icon_class",
        ),
    ]
