# Generated by Django 5.2.7 on 2025-10-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_remove_servicepage_badge_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicepage",
            name="description",
        ),
    ]
