# Generated by Django 5.2.7 on 2025-10-17 07:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_remove_servicepage_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicepage",
            name="features",
        ),
        migrations.RemoveField(
            model_name="servicepage",
            name="process_title",
        ),
        migrations.AlterField(
            model_name="servicepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 1),
                    ("feature_grid", 8),
                    ("process_list", 12),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "icon": "pilcrow",
                            "label": "Rich Text",
                        },
                    ),
                    1: ("services.blocks.ImageBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What's Included", "required": True},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The Bootstrap Icon class (e.g., 'bi bi-graph-up-arrow').",
                            "required": True,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    5: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_class", 3), ("title", 4), ("text", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("features", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Our Process", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("text", 5)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("steps", 11)]],
                        {},
                    ),
                },
            ),
        ),
    ]
