# Generated by Django 5.2.7 on 2025-10-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_remove_servicepage_features_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProcessStep",
        ),
    ]
