# Generated by Django 5.2.7 on 2025-10-22 08:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_delete_processstep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("image", 1),
                    ("image_url", 3),
                    ("feature_grid", 10),
                    ("process_list", 14),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "icon": "pilcrow",
                            "label": "Rich Text",
                        },
                    ),
                    1: ("services.blocks.ImageBlock", (), {}),
                    2: ("wagtail.blocks.URLBlock", (), {}),
                    3: ("wagtail.blocks.StructBlock", [[("image_url", 2)]], {}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What's Included", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The Bootstrap Icon class (e.g., 'bi bi-graph-up-arrow').",
                            "required": True,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": True},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("icon_class", 5), ("title", 6), ("text", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 4), ("features", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Our Process", "required": True},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 6), ("text", 7)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 11), ("steps", 13)]],
                        {},
                    ),
                },
            ),
        ),
    ]
