# Generated by Django 5.2.7 on 2025-10-16 08:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageTwo",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_heading",
                    models.CharField(
                        blank=True,
                        help_text="The main heading for the hero section.",
                        max_length=255,
                    ),
                ),
                (
                    "hero_subheading",
                    models.TextField(
                        blank=True,
                        help_text="The paragraph of text below the main heading.",
                    ),
                ),
                (
                    "hero_primary_cta_text",
                    models.CharField(blank=True, default="Get Started", max_length=100),
                ),
                (
                    "hero_secondary_cta_text",
                    models.CharField(blank=True, default="Our Work", max_length=100),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="The main visual for the hero section.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero_primary_cta_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page to link to for the primary button.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_secondary_cta_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page to link to for the secondary button.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="HeroStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "stat_number",
                    models.IntegerField(help_text="The number to count up to."),
                ),
                (
                    "stat_label",
                    models.CharField(
                        help_text="The text label for the number.", max_length=100
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_stats",
                        to="home.homepagetwo",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
