# Generated by Django 5.2.7 on 2025-10-16 08:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("portfolio", "0002_alter_portfoliopage_body"),
        ("services", "0009_alter_whyuspage_primary_cta_link_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_heading",
                    models.CharField(
                        blank=True,
                        help_text="The main heading for the hero section.",
                        max_length=255,
                    ),
                ),
                (
                    "hero_subheading",
                    models.TextField(
                        blank=True,
                        help_text="The paragraph of text below the main heading.",
                    ),
                ),
                (
                    "hero_primary_cta_text",
                    models.CharField(blank=True, default="Get Started", max_length=100),
                ),
                (
                    "hero_secondary_cta_text",
                    models.CharField(blank=True, default="Our Work", max_length=100),
                ),
                (
                    "about_subtitle",
                    models.CharField(
                        blank=True,
                        help_text="The small subtitle (e.g., 'Discover Our Story').",
                        max_length=100,
                    ),
                ),
                (
                    "about_title",
                    models.CharField(
                        blank=True,
                        help_text="The main title for the About section.",
                        max_length=255,
                    ),
                ),
                (
                    "about_text",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="The main paragraph of text."
                    ),
                ),
                (
                    "about_cta_text",
                    models.CharField(
                        blank=True, default="Discover More", max_length=100
                    ),
                ),
                ("services_title", models.CharField(blank=True, max_length=255)),
                ("services_subtitle", models.TextField(blank=True)),
                ("services_cta_title", models.CharField(blank=True, max_length=255)),
                ("services_cta_subtitle", models.TextField(blank=True)),
                (
                    "services_cta_button_text",
                    models.CharField(blank=True, max_length=50),
                ),
                ("services_cta_url", models.URLField(blank=True)),
                ("portfolio_title", models.CharField(blank=True, max_length=255)),
                ("portfolio_subtitle", models.TextField(blank=True)),
                ("portfolio_cta_title", models.CharField(blank=True, max_length=255)),
                ("portfolio_cta_subtitle", models.TextField(blank=True)),
                (
                    "portfolio_cta_button_text",
                    models.CharField(blank=True, max_length=50),
                ),
                ("portfolio_cta_url", models.URLField(blank=True)),
                (
                    "about_cta_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page to link to for the button.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "about_main_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="The large, primary image for the composition.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "about_secondary_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="The smaller, secondary image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "featured_why_us_section",
                    models.ForeignKey(
                        blank=True,
                        help_text='Choose a "Why Us" page to feature on the homepage.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="The main visual for the hero section.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero_primary_cta_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page to link to for the primary button.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_secondary_cta_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="The page to link to for the secondary button.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "portfolio_cta_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "portfolio_projects",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="portfolio.portfoliopage"
                    ),
                ),
                (
                    "services",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="services.servicepage"
                    ),
                ),
                (
                    "services_cta_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="AboutStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="The stat number or text (e.g., '20+' or '500+').",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="The label for the stat (e.g., 'Years of Expertise').",
                        max_length=100,
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_stats",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AboutFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The text for a single feature bullet point.",
                        max_length=255,
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_features",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="herostat",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hero_stats",
                to="home.homepage",
            ),
        ),
        migrations.DeleteModel(
            name="HomePageTwo",
        ),
    ]
