# Generated by Django 5.2.7 on 2025-10-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_homepage_aboutstat_aboutfeature_alter_herostat_page_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutfeature",
            name="text",
            field=models.CharField(
                default="About Text",
                help_text="The text for a single feature bullet point.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="aboutstat",
            name="label",
            field=models.CharField(
                default="Stat Label",
                help_text="The label for the stat (e.g., 'Years of Expertise').",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="aboutstat",
            name="number",
            field=models.CharField(
                default="0",
                help_text="The stat number or text (e.g., '20+' or '500+').",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="herostat",
            name="stat_label",
            field=models.CharField(
                default="Stat Label",
                help_text="The text label for the number.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="herostat",
            name="stat_number",
            field=models.IntegerField(
                default=0, help_text="The number to count up to."
            ),
        ),
    ]
