# Generated by Django 5.2.7 on 2025-10-16 09:32

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_aboutfeature_text_alter_aboutstat_label_and_more"),
        ("services", "0009_alter_whyuspage_primary_cta_link_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="services",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="services_cta_page",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="services_cta_url",
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_cta_link",
            field=models.ForeignKey(
                blank=True,
                help_text="The page to link the main CTA button to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_cta_button_text",
            field=models.CharField(
                blank=True, default="Get Started Today", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_cta_subtitle",
            field=models.TextField(
                blank=True,
                default="Let's discuss your project and create something amazing together",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_cta_title",
            field=models.CharField(
                blank=True,
                default="Ready to Transform Your Digital Presence?",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_subtitle",
            field=models.TextField(
                blank=True, help_text="The subtitle for the services section."
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services_title",
            field=models.CharField(blank=True, default="Services", max_length=100),
        ),
        migrations.CreateModel(
            name="ServiceCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="The Bootstrap Icon class (e.g., 'bi bi-palette').",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "show_badge",
                    models.BooleanField(
                        default=False,
                        help_text="Check to display a badge on this card.",
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        help_text="Text for the badge (e.g., 'Most Popular').",
                        max_length=50,
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose a page to link to for this service (e.g., a Service Detail Page).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="services.servicepage",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_cards",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
