# Generated by Django 5.2.7 on 2025-10-16 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_homepage_services_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_button_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_page",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_url",
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_primary_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page for the primary button (e.g., Contact Page).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_primary_text",
            field=models.CharField(
                blank=True, default="Start a Project", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_secondary_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page for the secondary button (e.g., Portfolio Page).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_secondary_text",
            field=models.CharField(blank=True, default="View All Work", max_length=50),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="portfolio_cta_subtitle",
            field=models.TextField(
                blank=True,
                default="Let's work together to bring your digital vision to life",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="portfolio_cta_title",
            field=models.CharField(
                blank=True, default="Ready to start your next project?", max_length=100
            ),
        ),
    ]
