# Generated by Django 5.2.7 on 2025-10-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_homepage_portfolio_cta_button_text_and_more"),
        ("products", "0008_pricingtier_nowpayment_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_primary_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_primary_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_secondary_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_secondary_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_subtitle",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_projects",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_subtitle",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_title",
        ),
        migrations.AddField(
            model_name="homepage",
            name="products_link",
            field=models.ForeignKey(
                blank=True,
                help_text="The page to link the main CTA button to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="products.productpage",
            ),
        ),
    ]
