# Generated by Django 5.2.7 on 2025-10-15 11:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliopage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading_block", 2),
                    ("paragraph_block", 3),
                    ("image_block", 6),
                    ("block_quote", 9),
                    ("embed_block", 10),
                    ("accordion", 16),
                    ("feature_list", 21),
                    ("spacer", 23),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a header size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("size", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "icon": "pilcrow",
                            "template": "portfolio/blocks/paragraph_block.html",
                        },
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5), ("attribution", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "label": "e.g. Mary Berry", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 7), ("attribute_name", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Insert an embed from URL",
                            "icon": "media",
                            "template": "portfolio/blocks/embed_block.html",
                        },
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Icon CSS class, e.g. 'bi bi-clipboard-data'",
                            "required": False,
                        },
                    ),
                    13: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 11), ("icon", 12), ("body", 13)]],
                        {},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: ("wagtail.blocks.StructBlock", [[("items", 15)]], {}),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "required": False},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Icon CSS class, e.g. 'bi bi-check2-circle'",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 11), ("icon", 18)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (19,), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 17), ("features", 20)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("xs", "Extra small (8px)"),
                                ("sm", "Small (16px)"),
                                ("md", "Medium (32px)"),
                                ("lg", "Large (48px)"),
                                ("xl", "Extra large (64px)"),
                            ],
                            "help_text": "Choose spacing size",
                        },
                    ),
                    23: ("wagtail.blocks.StructBlock", [[("size", 22)]], {}),
                },
                verbose_name="Page body",
            ),
        ),
    ]
