# Generated by Django 5.2.7 on 2025-10-14 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_header"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_primary_cta_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_primary_cta_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_primary_cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_secondary_cta_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_secondary_cta_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_secondary_cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_stat_1_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_stat_1_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_stat_2_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_stat_2_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_stat_3_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_stat_3_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
