# Generated by Django 5.2.7 on 2025-10-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_homepage_hero_image_homepage_hero_image_alt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hero_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_image_alt",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_primary_cta_page",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_primary_cta_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_primary_cta_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_secondary_cta_page",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_secondary_cta_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_secondary_cta_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_stat_1_label",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_stat_1_number",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_stat_2_label",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_stat_2_number",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_stat_3_label",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_stat_3_number",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_subtitle",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_title",
        ),
    ]
