# Generated by Django 5.2.7 on 2025-10-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_homepage_hero_image_homepage_hero_image_alt_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional hero image. If not provided, a default static image will be used.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_image_alt",
            field=models.CharField(
                blank=True, help_text="Alt text for the hero image.", max_length=255
            ),
        ),
    ]
