# Generated by Django 5.2.7 on 2025-10-14 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_homepage_hero_image_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_description",
            field=models.TextField(
                blank=True, help_text="Description for the About section."
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_feature_1",
            field=models.CharField(
                blank=True,
                help_text="First feature in the About section.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_feature_2",
            field=models.CharField(
                blank=True,
                help_text="Second feature in the About section.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_feature_3",
            field=models.CharField(
                blank=True,
                help_text="Third feature in the About section.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_main_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Main image for the About section.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_main_image_alt",
            field=models.CharField(
                blank=True, help_text="Alt text for the main image.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_secondary_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Secondary image for the About section.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_secondary_image_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for the secondary image.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_stat_1_label",
            field=models.CharField(
                blank=True,
                help_text="First stat label in the About section.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_stat_1_number",
            field=models.CharField(
                blank=True,
                help_text="First stat number in the About section.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_stat_2_label",
            field=models.CharField(
                blank=True,
                help_text="Second stat label in the About section.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_stat_2_number",
            field=models.CharField(
                blank=True,
                help_text="Second stat number in the About section.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_subtitle",
            field=models.CharField(
                blank=True, help_text="Subtitle for the About section.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_title",
            field=models.CharField(
                blank=True, help_text="Title for the About section.", max_length=255
            ),
        ),
    ]
