# Generated by Django 5.2.7 on 2025-10-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_homepage_about_description_homepage_about_feature_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="about_main_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_secondary_image",
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_main_image_url",
            field=models.CharField(
                blank=True,
                help_text="URL for the main static image in the About section.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_secondary_image_url",
            field=models.CharField(
                blank=True,
                help_text="URL for the secondary static image in the About section.",
                max_length=255,
            ),
        ),
    ]
