# Generated by Django 5.2.7 on 2025-10-14 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_homepage_about_main_image_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="Bootstrap icon class for the service (e.g. 'bi bi-palette')",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "badge_text",
                    models.CharField(
                        blank=True,
                        help_text="Optional badge text (e.g. 'Most Popular')",
                        max_length=50,
                    ),
                ),
                (
                    "service_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL for Learn More if no page chosen.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for sorting services."
                    ),
                ),
                (
                    "service_page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Internal page to link to for Learn More.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.AddField(
            model_name="homepage",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select services to display on the homepage.",
                to="base.service",
            ),
        ),
    ]
