# Generated by Django 5.2.7 on 2025-10-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_standardpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="about_main_image_alt",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_main_image_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_secondary_image_alt",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_secondary_image_url",
        ),
    ]
