# Generated by Django 5.2.7 on 2025-10-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_testimonial"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="services",
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.AddField(
            model_name="homepage",
            name="services",
            field=models.ForeignKey(
                blank=True,
                help_text="Services featured section for the homepage. Will display up to six child items.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Services",
            ),
        ),
    ]
