# Generated by Django 5.2.7 on 2025-10-15 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_remove_homepage_services_homepage_services_subtitle_and_more"),
        ("services", "0006_servicepage_contact_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="services",
            field=models.ForeignKey(
                blank=True,
                help_text="Services featured section for the homepage. Will display up to six child items.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="services.servicepage",
                verbose_name="Services",
            ),
        ),
    ]
