# Generated by Django 5.2.7 on 2025-10-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_homepage_services"),
        ("services", "0006_servicepage_contact_form"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="services",
        ),
        migrations.AddField(
            model_name="homepage",
            name="services",
            field=models.ManyToManyField(blank=True, to="services.servicepage"),
        ),
    ]
