# Generated by Django 5.2.7 on 2025-10-15 09:38

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_remove_homepage_services_homepage_services"),
        ("services", "0006_servicepage_contact_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="services",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="services.servicepage"
            ),
        ),
    ]
