# Generated by Django 5.2.7 on 2025-10-15 11:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_alter_standardpage_body"),
        ("portfolio", "0002_alter_portfoliopage_body"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_button_text",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_projects",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="portfolio.portfoliopage"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
