# Generated by Django 5.2.7 on 2025-10-15 12:19

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_homepage_portfolio_cta_button_text_and_more"),
        ("portfolio", "0002_alter_portfoliopage_body"),
        ("wagtailcore", "0095_groupsitepermission"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_button_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_page",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_subtitle",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_cta_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_projects",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_subtitle",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="portfolio_title",
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_cta_primary_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_cta_primary_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_cta_primary_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_cta_secondary_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_cta_secondary_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_cta_secondary_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_right_lead",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_right_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_showcase_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_showcase_image_alt",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_us_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="WhyUsCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Icon CSS class, e.g. 'bi bi-palette-fill'",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="why_us_cards",
                        to="base.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WhyUsListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Icon CSS class, e.g. 'bi bi-check-circle-fill'",
                        max_length=100,
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True)),
                ("portfolio_title", models.CharField(blank=True, max_length=255)),
                ("portfolio_subtitle", models.TextField(blank=True)),
                ("portfolio_cta_title", models.CharField(blank=True, max_length=255)),
                ("portfolio_cta_subtitle", models.TextField(blank=True)),
                (
                    "portfolio_cta_button_text",
                    models.CharField(blank=True, max_length=50),
                ),
                ("portfolio_cta_url", models.URLField(blank=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="why_us_list_items",
                        to="base.homepage",
                    ),
                ),
                (
                    "portfolio_cta_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "portfolio_projects",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="portfolio.portfoliopage"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
