# Generated by Django 5.2.7 on 2025-10-15 12:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_remove_homepage_portfolio_cta_button_text_and_more"),
        ("portfolio", "0002_alter_portfoliopage_body"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="whyuslistitem",
            name="page",
        ),
        migrations.RemoveField(
            model_name="whyuslistitem",
            name="portfolio_cta_page",
        ),
        migrations.RemoveField(
            model_name="whyuslistitem",
            name="portfolio_projects",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_cta_primary_page",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_cta_primary_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_cta_primary_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_cta_secondary_page",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_cta_secondary_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_cta_secondary_url",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_right_lead",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_right_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_showcase_image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_showcase_image_alt",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_subtitle",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_title",
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_button_text",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_cta_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_projects",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="portfolio.portfoliopage"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_subtitle",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="portfolio_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name="WhyUsCard",
        ),
        migrations.DeleteModel(
            name="WhyUsListItem",
        ),
    ]
