# Generated by Django 5.2.7 on 2025-10-15 12:29

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_remove_whyuslistitem_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="why_us_content",
            field=wagtail.fields.StreamField(
                [("feature", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Icon class, e.g. 'bi bi-check-circle-fill'",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("text", 1), ("icon", 2)]],
                        {},
                    ),
                },
                verbose_name="Why Us content",
            ),
        ),
        migrations.CreateModel(
            name="WhyUsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon CSS class e.g. 'bi bi-award-fill'",
                        max_length=255,
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="why_us_items",
                        to="base.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
