# Generated by Django 5.2.7 on 2025-10-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_homepage_why_us_content_whyusitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="why_us_content",
        ),
    ]
