# Generated by Django 5.2.7 on 2025-10-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_remove_homepage_why_us_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WhyUsItem",
        ),
    ]
