# Generated by Django 5.2.7 on 2025-10-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_delete_whyusitem"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="featured_why_us_section",
            field=models.ForeignKey(
                blank=True,
                help_text='Choose a "Why Us" page to feature on the homepage.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
