# Generated by Django 5.2.7 on 2025-10-15 17:01

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_homepage_featured_why_us_section"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Sigmora",
                        help_text="The name of the site, displayed in the footer.",
                        max_length=255,
                    ),
                ),
                (
                    "about_text",
                    wagtail.fields.RichTextField(
                        help_text="The contact information or 'about' text."
                    ),
                ),
                (
                    "footer_links",
                    wagtail.fields.StreamField(
                        [("column", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 100, "required": True},
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("link_text", 0), ("link_page", 1)]],
                                {},
                            ),
                            3: ("wagtail.blocks.ListBlock", (2,), {}),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("links", 3)]],
                                {},
                            ),
                        },
                        help_text="Add columns of links to the footer.",
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(blank=True, default="Copyright", max_length=255),
                ),
                (
                    "credits_text",
                    wagtail.fields.RichTextField(
                        blank=True,
                        default="Designed by <a>Sigmora</a>",
                        help_text="The credits line at the bottom of the footer.",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The full URL of the social media profile."
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="The Bootstrap Icon class (e.g., 'bi bi-twitter-x').",
                        max_length=100,
                    ),
                ),
                (
                    "footer_settings",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="base.footersettings",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
