# Generated by Django 5.2.7 on 2025-10-16 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_footersettings_sociallink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standardpage",
            name="body",
        ),
    ]
