# Generated by Django 5.2.7 on 2025-10-16 07:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0029_standardpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpage",
            name="subtitle",
            field=models.TextField(
                blank=True,
                help_text="A short subtitle that appears under the main page title.",
            ),
        ),
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("image", 3), ("quote", 6), ("html", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "icon": "pilcrow",
                            "label": "Rich Text",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Add a caption for the image.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("caption", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {"required": True, "rows": 3}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("quote_text", 4), ("author", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"icon": "code", "label": "Raw HTML"},
                    ),
                },
                help_text="The main content of the page, built from a variety of blocks.",
            ),
        ),
    ]
