# Generated by Django 5.2.7 on 2025-10-16 08:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_standardpage_subtitle_alter_standardpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standardpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", 0),
                    ("heading", 3),
                    ("image", 6),
                    ("quote", 9),
                    ("html", 10),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                            ],
                            "icon": "pilcrow",
                            "label": "Rich Text",
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a header size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 1), ("size", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Add a caption for the image.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"required": True, "rows": 3}),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 100, "required": False},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("quote_text", 7), ("author", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.RawHTMLBlock",
                        (),
                        {"icon": "code", "label": "Raw HTML"},
                    ),
                },
                help_text="The main content of the page, built from a variety of blocks.",
            ),
        ),
    ]
