# Generated by Django 5.2.7 on 2025-10-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0031_alter_standardpage_body"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
