# Generated by Django 5.2.7 on 2025-10-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_order_paymentsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentsettings",
            name="site",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="PaymentSettings",
        ),
    ]
