# Generated by Django 5.2.7 on 2025-10-21 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_paymentsettings_site_delete_order_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlistingpage",
            name="product_cta_primary_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page for the primary button (e.g., Contact Page).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="productlistingpage",
            name="product_cta_primary_text",
            field=models.CharField(
                blank=True, default="Start a Project", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="productlistingpage",
            name="product_cta_secondary_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page for the secondary button (e.g., Portfolio Page).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="productlistingpage",
            name="product_cta_secondary_text",
            field=models.CharField(blank=True, default="View All Work", max_length=50),
        ),
    ]
