# Generated by Django 5.2.7 on 2025-10-21 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productlistingpage_product_cta_primary_link_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="productlistingpage",
            name="product_cta_subtitle",
            field=models.TextField(
                blank=True,
                default="Let's work together to bring your digital vision to life",
            ),
        ),
        migrations.AddField(
            model_name="productlistingpage",
            name="product_cta_title",
            field=models.CharField(
                blank=True, default="Ready to start your next project?", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="productlistingpage",
            name="product_cta_secondary_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Choose a page for the secondary button (e.g., Pricing Page).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
