# Generated by Django 5.2.7 on 2025-10-21 13:29

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productlistingpage_product_cta_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("accordion_section", 2), ("rich_text", 3), ("image", 4)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {"icon": "collapse-down", "label": "Accordion Section"},
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="client_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="lead_paragraph",
            field=models.TextField(
                blank=True,
                help_text="The introductory paragraph below the title.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="pricing_subtitle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="pricing_title",
            field=models.CharField(
                blank=True, default="Pricing", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="project_date",
            field=models.DateField(blank=True, null=True, verbose_name="Project date"),
        ),
        migrations.AlterField(
            model_name="productpage",
            name="project_website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
