# Generated by Django 5.2.7 on 2025-10-21 13:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0006_alter_productpage_body_alter_productpage_client_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("accordion", 5), ("rich_text", 6), ("image", 7)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "blank": True,
                            "help_text": "Icon CSS class, e.g. 'bi bi-clipboard-data'",
                            "required": False,
                        },
                    ),
                    2: ("wagtail.blocks.RichTextBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("icon", 1), ("body", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.ListBlock", (3,), {}),
                    5: ("wagtail.blocks.StructBlock", [[("items", 4)]], {}),
                    6: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"icon": "image"},
                    ),
                },
            ),
        ),
    ]
