# Generated by Django 5.2.7 on 2025-10-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_productpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricingtier",
            name="nowpayment_url",
            field=models.URLField(max_length=100, null=True),
        ),
    ]
