# Generated by Django 5.2.7 on 2025-10-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_productimage_image_url_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
